server:
  port: 8002
#mybatis
mybatis:
  type-aliases-package: com.dhr.springcloud.entity
  config-location:  classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#spring
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/practice2?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 130124010007
#Eureka配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8002 #修改eureka上默认的描述信息！
#info配置
info:
  app.name: donghuarui-springcloud
  company.name: www.tech.qj.com