server:
  port: 9527
spring:
  application:
    name: springcloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
  instance:
      instance-id: zuul9527.com
      prefer-ip-address: true
info:
  app.name: dhr-springcloud
  company-name: dhrstud
zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: springcloud-provider-dept   #需要忽略的服务名  所有可以写成  "*"
  prefix: /dhr